### ISSUE TITLE
大佬，能不能推出一个纯windows的启动方式， wsl的N卡驱动安装不上

### ISSUE THREAD

**Issue by a793181018** [codefuse-ai/codefuse-chatbot#2]

**Comment by lightislost** [comment]
可以直接在windows上启动的，只需要将server_config.py里面的与容器启动相关的配置修改成false

# 是否用容器来启动服务
DOCKER_SERVICE = False
# 是否采用容器沙箱
SANDBOX_DO_REMOTE = False

**Comment by a793181018** [comment]
大佬，那怎么启动呢

**Comment by a793181018** [comment]
例外，多显卡共同部署该怎么改配置呢或者代码呢

**Comment by a793181018** [comment]
已经通过修改代码参数实现了多显卡共同部署，但Web界面为404

**Comment by lightislost** [comment]
参考readme 修改完 model_config.py 和server_config.py 之后
执行下面代码可以一键启动
```
cd  examples 
python start.py
```

**Comment by a793181018** [comment]
不行，启动Start.py后报错：
Traceback (most recent call last):
  File "D:\AITransformers\codefuse-chatbot\examples\start.py", line 85, in <module>
    client = docker.from_env()
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\docker\client.py", line 96, in from_env
    return cls(
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\docker\client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\docker\api\client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\docker\api\client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', '系统找不到指定的文件。')

**Comment by a793181018** [comment]
读取docker环境时报错

**Comment by a793181018** [comment]
报错如下：
2023-11-29 07:06:16.111 Uncaught app exception
Traceback (most recent call last):
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\AITransformers\codefuse-chatbot\examples\webui.py", line 26, in <module>
    api = ApiRequest(no_remote_api=NO_REMOTE_API)
  File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\webui\utils.py", line 78, in __init__
    self.dataChat = DataChat()
  File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\chat\data_chat.py", line 146, in __init__
    self.codebox = PyCodeBox(
  File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\sandbox\pycodebox.py", line 34, in __init__
    asyncio.run(self.astart())
  File "D:\anaconda3\envs\devopsgpt\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\anaconda3\envs\devopsgpt\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\sandbox\pycodebox.py", line 345, in astart
    port_status = await self._acheck_port()
  File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\sandbox\pycodebox.py", line 249, in _acheck_port
    async with session.get(f"{self.remote_ip}:{self.remote_port}", timeout=270) as resp:
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\aiohttp\client.py", line 1187, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\aiohttp\client.py", line 601, in _request
    await resp.start(conn)
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\aiohttp\client_reqrep.py", line 980, in start
    self._continue = None
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\aiohttp\helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by a793181018** [comment]
核心还是docker环境没有检测到的原因

**Comment by lightislost** [comment]
了解了，你的环境没有docker。这个脚本之后会重新更新下

**Comment by lightislost** [comment]
可以直接在windows上启动的，只需要将server_config.py里面的与容器启动相关的配置修改成false

```python
# 屏蔽容器服务执行
# 是否用容器来启动服务
DOCKER_SERVICE = False
# 是否采用容器沙箱`
SANDBOX_DO_REMOTE = False
```
```python
# 启动start.py可以启动相关依赖
cd  examples 
python start.py
```

**Comment by a793181018** [comment]
出现以下报错：
File "D:\anaconda3\envs\devopsgpt\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "D:\AITransformers\codefuse-chatbot\examples\webui.py", line 25, in <module>
    api = ApiRequest(base_url="http://127.0.0.1:7861", no_remote_api=NO_REMOTE_API)
File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\webui\utils.py", line 77, in __init__
    self.dataChat = DataChat()
File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\chat\data_chat.py", line 146, in __init__
    self.codebox = PyCodeBox(
File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\sandbox\pycodebox.py", line 34, in __init__
    asyncio.run(self.astart())
File "D:\anaconda3\envs\devopsgpt\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
File "D:\anaconda3\envs\devopsgpt\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\sandbox\pycodebox.py", line 345, in astart
    port_status = await self._acheck_port()
File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\sandbox\pycodebox.py", line 249, in _acheck_port
    async with session.get(f"{self.remote_ip}:{self.remote_port}", timeout=270) as resp:
File "D:\anaconda3\envs\devopsgpt\lib\site-packages\aiohttp\client.py", line 1187, in __aenter__
    self._resp = await self._coro
File "D:\anaconda3\envs\devopsgpt\lib\site-packages\aiohttp\client.py", line 601, in _request
    await resp.start(conn)
File "D:\anaconda3\envs\devopsgpt\lib\site-packages\aiohttp\client_reqrep.py", line 965, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
File "D:\anaconda3\envs\devopsgpt\lib\site-packages\aiohttp\streams.py", line 622, in read
    await self._waiter

**Comment by lightislost** [comment]
1、server_config.py 可以贴一下
2、确认  http://localhost:5050  是否能打开一个notebook页面，如果不能。调试下notebook启动方式，执行 start.py 的时候应该是有条日志为 notebook 的启动命令的
3、确认是否存在端口冲突。替换 server_config.py 中冲突的端口
4、python stop.pyh 后重新执行 python start.py

**Comment by a793181018** [comment]
from .model_config import LLM_MODEL, LLM_DEVICE
import os

# API 是否开启跨域，默认为False，如果需要开启，请设置为True
# is open cross domain
OPEN_CROSS_DOMAIN = False
# 是否用容器来启动服务
DOCKER_SERVICE = False
# 是否采用容器沙箱
SANDBOX_DO_REMOTE = False
# 是否采用api服务来进行
NO_REMOTE_API = False
# 各服务器默认绑定host
DEFAULT_BIND_HOST = "127.0.0.1"

# 
CONTRAINER_NAME = "devopsgpt_webui"
IMAGE_NAME = "devopsgpt:py39"

# webui.py server
WEBUI_SERVER = {
    "host": DEFAULT_BIND_HOST,
    "port": 8501,
    "docker_port": 8501
}

# api.py server
API_SERVER = {
    "host": DEFAULT_BIND_HOST,
    "port": 7861,
    "docker_port": 7861
}

# sdfile_api.py server
SDFILE_API_SERVER = {
    "host": DEFAULT_BIND_HOST,
    "port": 7862,
    "docker_port": 7862
}

# fastchat openai_api server
FSCHAT_OPENAI_API = {
    "host": DEFAULT_BIND_HOST,
    "port": 8888,  # model_config.llm_model_dict中模型配置的api_base_url需要与这里一致。
    "docker_port": 8888,  # model_config.llm_model_dict中模型配置的api_base_url需要与这里一致。
}

# sandbox api server
SANDBOX_CONTRAINER_NAME = "devopsgpt_sandbox"
SANDBOX_IMAGE_NAME = "devopsgpt:py39"
SANDBOX_HOST = os.environ.get("SANDBOX_HOST") or DEFAULT_BIND_HOST # "172.25.0.3"
SANDBOX_SERVER = {
    "host": f"http://{SANDBOX_HOST}",
    "port": 5050,
    "docker_port": 5050,
    "url": f"http://{SANDBOX_HOST}:5050",
    "do_remote": SANDBOX_DO_REMOTE,
}

# fastchat model_worker server
# 这些模型必须是在model_config.llm_model_dict中正确配置的。
# 在启动startup.py时，可用通过`--model-worker --model-name xxxx`指定模型，不指定则为LLM_MODEL
FSCHAT_MODEL_WORKERS = {
    LLM_MODEL: {
        "host": DEFAULT_BIND_HOST,
        "port": 20002,
        "device": LLM_DEVICE,
        # todo: 多卡加载需要配置的参数
        "gpus": None,
        "numgpus": 1,
        # 以下为非常用参数，可根据需要配置
        # "max_gpu_memory": "20GiB",
        # "load_8bit": False,
        # "cpu_offloading": None,
        # "gptq_ckpt": None,
        # "gptq_wbits": 16,
        # "gptq_groupsize": -1,
        # "gptq_act_order": False,
        # "awq_ckpt": None,
        # "awq_wbits": 16,
        # "awq_groupsize": -1,
        # "model_names": [LLM_MODEL],
        # "conv_template": None,
        # "limit_worker_concurrency": 5,
        # "stream_interval": 2,
        # "no_register": False,
    },
}

# fastchat multi model worker server
FSCHAT_MULTI_MODEL_WORKERS = {
    # todo
}

# fastchat controller server
FSCHAT_CONTROLLER = {
    "host": DEFAULT_BIND_HOST,
    "port": 20001,
    "dispatch_method": "shortest_queue",
}


# 以下不要更改
def fschat_controller_address() -> str:
    host = FSCHAT_CONTROLLER["host"]
    port = FSCHAT_CONTROLLER["port"]
    return f"http://{host}:{port}"


def fschat_model_worker_address(model_name: str = LLM_MODEL) -> str:
    if model := FSCHAT_MODEL_WORKERS.get(model_name):
        host = model["host"]
        port = model["port"]
        return f"http://{host}:{port}"


def fschat_openai_api_address() -> str:
    host = FSCHAT_OPENAI_API["host"]
    port = FSCHAT_OPENAI_API["port"]
    return f"http://{host}:{port}"


def api_address() -> str:
    host = API_SERVER["host"]
    port = API_SERVER["port"]
    return f"http://{host}:{port}"


def webui_address() -> str:
    host = WEBUI_SERVER["host"]
    port = WEBUI_SERVER["port"]
    return f"http://{host}:{port}"

**Comment by a793181018** [comment]
http://localhost:5050/ 打不开

**Comment by a793181018** [comment]
能正常打开页面了
在点击 知识库管理 选项时
但有以下报错：
Traceback (most recent call last):
  File "D:\anaconda3\envs\devopsgpt\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\AITransformers\codefuse-chatbot\examples\webui.py", line 90, in <module>
    pages[selected_page]["func"](api)
  File "D:\AITransformers\codefuse-chatbot\dev_opsgpt\webui\document.py", line 106, in knowledge_page
    index=embed_models.index(EMBEDDING_MODEL),
ValueError: 'D:\\AITransformers\\codefuse-chatbot\text2vec-base-chinese' is not in list

**Comment by lightislost** [comment]
你配置没写对，可以看下readme的配置介绍。

```
1、EMBEDDING_MODEL   填写  embedding_model_dict 里面的key

2、把向量模型放到  D:\AITransformers\codefuse-chatbot\embedding_models\text2vec-base-chinese

embedding_model_dict  的key-value设置成这样就可以了，完整路径不用填写

"text2vec-base": "text2vec-base-chinese",
```

这个issue 就关了
