### ISSUE TITLE
安装好环境和docker，cd examples，运行python start.py报错  NameError: name 'is_running_in_docker' is not defined

### ISSUE THREAD

**Issue by quida01** [codefuse-ai/codefuse-chatbot#8]
python start.py
Traceback (most recent call last):
  File "/media/models/model-tools/codefuse-chatbot-main/examples/start.py", line 11, in <module>
    from configs.model_config import USE_FASTCHAT, JUPYTER_WORK_PATH
  File "/media/models/model-tools/codefuse-chatbot-main/configs/__init__.py", line 1, in <module>
    from .model_config import *
  File "/media/models/model-tools/codefuse-chatbot-main/configs/model_config.py", line 42, in <module>
    embedding_model_dict = {k: f"/home/user/chatbot/embedding_models/{v}" if is_running_in_docker() else f"{LOCAL_MODEL_DIR}/{v}" for k, v in embedding_model_dict.items()}
  File "/media/models/model-tools/codefuse-chatbot-main/configs/model_config.py", line 42, in <dictcomp>
    embedding_model_dict = {k: f"/home/user/chatbot/embedding_models/{v}" if is_running_in_docker() else f"{LOCAL_MODEL_DIR}/{v}" for k, v in embedding_model_dict.items()}
NameError: name 'is_running_in_docker' is not defined

**Comment by lightislost** [comment]
is_running_in_docker 没从 configs/utils.py 中导入，已修复
